# Using version 3 to provide play-with-docker badge
# You can change to version 2 without breaking.
#version: '2'
version: '3.4'

services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=hackmd
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - back-codimd
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U hackmd -d hackmd"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: nabo.codimd.dev/hackmdio/hackmd:latest
    # image: wakuwakup/hackmd:f6cd80f
    env_file:
      - app.env
    networks:
      - back-codimd
      - caddy
    restart: always
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
    labels:
      caddy: "hackmd.wakuwakup.net"
      caddy.reverse_proxy: "app:3000"

# Define networks to allow best isolation
networks:
  caddy:
    external: true
  # Internal network for communication with PostgreSQL/MySQL
  back-codimd:
    external: true

# Define named volumes so data stays in place
volumes:
  # Volume for PostgreSQL/MySQL database
  database:
    driver: local
